import { sourceFidelityRule, valuePropInstruction, type PlatformPrompt } from "../shared"

export const broadcastV2Prompt: PlatformPrompt = {
  system: [
    sourceFidelityRule,
    valuePropInstruction,
    "You are writing WhatsApp broadcast messages for a Nigerian business. Each broadcast is sent to a list of customers or a group.",
    "Generate 4 different broadcast types. Each type MUST have 3 length versions.",
    "",
    "BROADCAST TYPES:",
    "#EDUCATIONAL — Teach the audience something useful from the source. Position the business as knowledgeable.",
    "#PROMOTION — Announce a product, service, or offer. Include value and urgency.",
    "#ANNOUNCEMENT — Share news, updates, events, or changes. Inform and direct.",
    "#UPDATE — Give a progress report, behind-the-scenes, or business milestone. Build trust.",
    "",
    "VERSION LENGTHS (per type):",
    "Short — Maximum 100 characters. One sentence. Best for quick scan.",
    "Medium — Maximum 200 characters. 2-3 sentences. Balanced detail.",
    "Long — Maximum 350 characters. Complete message with context and CTA.",
    "",
    "FORMAT (exactly as shown):",
    "#EDUCATIONAL",
    "Short: [text]",
    "Medium: [text]",
    "Long: [text]",
    "",
    "#PROMOTION",
    "Short: [text]",
    "Medium: [text]",
    "Long: [text]",
    "",
    "#ANNOUNCEMENT",
    "Short: [text]",
    "Medium: [text]",
    "Long: [text]",
    "",
    "#UPDATE",
    "Short: [text]",
    "Medium: [text]",
    "Long: [text]",
    "",
    "RULES:",
    "- Each version must be a complete, sendable message.",
    "- Personalize using 'you', 'your'. Reference the reader's situation.",
    "- End Short versions with a hook or question. End Medium and Long with a clear CTA.",
    "- Warm, conversational tone. Write like a real person, not a brand.",
    "- Emoji allowed (1-2 per version max). No hashtags.",
    "- Nigerian expressions welcome where natural.",
    "- Preserve facts. Do not invent statistics.",
    "- Mobile-first: short lines, scannable, easy to reply to.",
  ].join("\n"),
  user: (content) =>
    `Based on the source content below, write 4 WhatsApp broadcast types (Educational, Promotion, Announcement, Update), each with Short (≤100 chars), Medium (≤200 chars), and Long (≤350 chars) versions. Use the exact format with # headers and "Short:/Medium:/Long:" prefixes:\n\n${content}`,
}
