export type {
  WhatsAppConfig,
  MessageStatus,
  SendResult,
  WACampaignInput,
  WACampaign,
  WACampaignDoc,
  WAStatusInput,
  WAStatus,
  WAStatusDoc,
  WABroadcastInput,
  WABroadcast,
  WABroadcastDoc,
  BroadcastCategory,
  WAFunnelInput,
  WAFunnel,
  WAFunnelDoc,
  FunnelStage,
  WAFollowUpInput,
  WAFollowUp,
  WAFollowUpDoc,
  FollowUpType,
  WARecipientInput,
  WARecipient,
  WARecipientDoc,
} from "./types"

export type { IWhatsAppService } from "./service"
export { MockWhatsAppService, WhatsAppBusinessApiService, getWhatsAppService, resetWhatsAppService } from "./service"

export {
  createCampaign,
  updateCampaign,
  deleteCampaign,
  getCampaign,
  listCampaigns,
  createStatus,
  createStatuses,
  updateStatus,
  listStatuses,
  createBroadcast,
  createBroadcasts,
  updateBroadcast,
  listBroadcasts,
  createFunnelStep,
  createFunnelSteps,
  updateFunnelStep,
  listFunnelSteps,
  createFollowUp,
  createFollowUps,
  updateFollowUp,
  listFollowUps,
  createRecipient as createWARecipient,
  updateRecipient as updateWARecipient,
  deleteRecipient as deleteWARecipient,
  listRecipients as listWARecipients,
} from "./db"
